settings:
  win-msg: "&c&lFACTIONS &8&l▶ &7You have won &a$%amount%"
  loss-msg: "&c&lFACTIONS &8&l▶ &7You have lost &c$%amount%"
  remove-msg: "&c&lFACTIONS &8&l▶ &7Successfully created coin flip! &c/coinflip remove &7to remove coin flip."
  broadcast:
    minimum: 25000
    message: "&4&lCOINFLIP &8&l▶ &c%winner% &7has just beat &c%loser% &7in a &a$%amount% &7coin flip!"

guis:
  main-gui:
    title: "Coin Flip Matches"
    item-name: "%color%&l%player%"
    item-lore:
      - " "
      - "&7&lWager"
      - "&a$%amount%"
      - " "
      - "&7&lColor Chosen"
      - "&7%color_name%"
      - " "
      - "&7&lWin/Loss Ratio"
      - "&7(%ratio%&7)"