name: CosmosCoinflip
version: '${project.version}'
main: me.rages.cosmosconflip.CoinflipPlugin
api-version: 1.18
commands:
  coinflip:
    description: Your description
    permission: cosmosconflip.create